import { Footer } from "@/components/layout/footer";
import { Header } from "@/components/layout/header";
import { CallToAction } from "@/templates/sections";
import { Inter, PT_Sans_Caption } from "next/font/google";
import "@/styles/globals.css";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

const inter = Inter({
	subsets: ["latin"],
	weight: ["400", "500"],
	variable: "--font-inter",
});

const ptSansCaption = PT_Sans_Caption({
	subsets: ["latin"],
	weight: "700",
	variable: "--font-sans",
});

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="pt-BR">
			<body>
				<div
					className={`${inter.variable} ${ptSansCaption.variable} relative flex min-h-screen flex-col bg-gray-700 font-inter`}
				>
					<Header />
					<main className="flex-1 flex flex-col mt-10 mb-12">{children}</main>
					<CallToAction />
					<Footer />
				</div>
			</body>
		</html>
	);
}
